# Generated by Django 6.1.1 on 2026-10-05 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.TextField(max_length=255, verbose_name="Nombre")),
                (
                    "descripcion",
                    models.TextField(max_length=255, verbose_name="Descripcion"),
                ),
                ("created_at", models.DateTimeField(verbose_name="Fecha de creación")),
                (
                    "updated_at",
                    models.DateTimeField(verbose_name="Fecha de actualización"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "descripcion",
                    models.TextField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="descripcion",
                    ),
                ),
                (
                    "precio_compra",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Precio de compra"
                    ),
                ),
                (
                    "precio_venta",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Precio de venta"
                    ),
                ),
                ("stock", models.PositiveIntegerField(verbose_name="Stock")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="productos",
                        to="catalogo.categoria",
                        verbose_name="Categoría",
                    ),
                ),
            ],
        ),
    ]
